@baseURL = http://localhost:3333

# @name create_trip
POST {{baseURL}}/trips
Content-Type: application/json

{
  "destination": "Florianópolis",
  "starts_at": "2024-07-15 18:00:00",
  "ends_at": "2024-07-21 12:40:00",
  "owner_name": "Gabriel Martins",
  "owner_email": "gabrieltest@gmail.com",
  "emails_to_invite": [
    "jessica.white44@yahoo.com",
    "justus_hessel81@hotmail.com",
    "erik_leffler3@gmail.com"
  ]
}